version: '3.8'

services:
  app:
    build: .
    container_name: pdf-kg-extractor
    ports:
      - "8000:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - DEBUG=False
      - HOST=0.0.0.0
      - PORT=8000
      - DATABASE_URL=sqlite:///./data/kg_system.db
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Optional: Add database service if needed
  # postgres:
  #   image: postgres:15
  #   container_name: pdf-kg-postgres
  #   environment:
  #     POSTGRES_DB: kg_system
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

  # Optional: Add Redis for caching
  # redis:
  #   image: redis:7-alpine
  #   container_name: pdf-kg-redis
  #   ports:
  #     - "6379:6379"

volumes:
  postgres_data:
